# Generated by Django 4.1.7 on 2023-04-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_CRUD', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='Age',
            field=models.IntegerField(),
        ),
    ]
